### ISSUE TITLE
There should be an option in Postgres CRD to drop database and role on deletion

### ISSUE THREAD

**Issue by arnarg** [movetokube/postgres-operator#10]
This could be a variable `spec.keepResources` in the `Postgres` CRD of type boolean.

When set to true it should keep the owner group role and database on deletion. This should be default.

When set to false it should drop the owner group role and database on deletion.

**Comment by arnarg** [comment]
@hitman99 I'm having a bit of trouble with this like the issue is worded now.

Bool properties in golang will always (as far as I'm aware) default to false when using json unmarshal. Thus it's quite difficult to see if the user left the field unspecified or he set it to false on purpose.

I say we turn the wording around, like `dropOnDelete` or something like that. What do you think?

**Comment by hitman99** [comment]
@arnarg I see your point. Reword sounds the property as you suggested seems a good way to workaround it. In addition, we could look into [defaulting](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#defaulting)

**Comment by arnarg** [comment]
> In addition, we could look into [defaulting](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#defaulting)

Yeah I noticed that in the documentation as well when researching this but it's currently in beta in 1.16.

The only other way I can think of is to use [mutating admission webhook](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#mutatingadmissionwebhook) but I think that adds too much complexity for one boolean variable.

**Comment by hitman99** [comment]
Yeah, it's only beta in 1.16. For now your suggestion seems to be the best (rewording the property).
