### ISSUE TITLE
PostgresUser CRs should have a OwnerReference to the Postgres CR it references

### ISSUE THREAD

**Issue by arnarg** [movetokube/postgres-operator#12]
PostgresUsers should be garbage collected by Kubernetes if the Postgres they reference are deleted.

**Comment by arnarg** [comment]
Maybe [foreground cascading deletion](https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/#foreground-cascading-deletion) makes sense in this case

**Comment by hitman99** [comment]
Yeah, looks good.

**Comment by hitman99** [comment]
Done 1002a2c4afa53908c6e34532a1b38b338669434d
