### ISSUE TITLE
Compare to kubehippie/database-controller

### ISSUE THREAD

**Issue by razum2um** [movetokube/postgres-operator#4]
I discovered you on operatorhub.io, but also found https://github.com/kubehippie/database-controller

As I see both operators do almost the same, but they support both pg & mysql and is a bit older - was anything wrong with them?

**Comment by hitman99** [comment]
Hi, not sure about the database-controller, I have not tried it so cannot really comment. Mysql would not be the problem to implement into postgres-operator, but I would rather make them separate.

**Comment by hitman99** [comment]
Closing this as it's not really an issue with the operator itself
