### ISSUE TITLE
When recreating a previously deleted Postgres CR tables in the database are not owned by the group role

### ISSUE THREAD

**Issue by arnarg** [movetokube/postgres-operator#8]
Using the following `Postgres` CR as an example:

```yaml
apiVersion: db.movetokube.com/v1alpha1
kind: Postgres
metadata:
  name: my-db
spec:
  database: test-db
```

1. Apply the manifest
    -  A database with the name `my-db` and role with name `role-db-group` is created
2. Use the role (through a `PostgresRole`) to create a table in `my-db` database
3. Delete the `Postgres` CR
    - All objects owned by `my-db-group` are transferred to the operator's role and the role is dropped, database ownership is transferred to the operator's role
4. Recreate the `Postgres` CR
    - `my-db` already exists so its ownership is transferred to new group role `my-db-group` **but all tables in the database are still owned by the operator's role**

**Comment by hitman99** [comment]
I think this problem should be solved by more generic approach, or differnet aproach entirely. In this case it is tables, but the same thing applies for sequences, stored procedures, schemas, etc. 

One option would be to retain master role (non-login group role created by the operator) created by `Postgres` CR, as long as the database itself exists. This means that `Postgres` CR should have a finalizer that would prevent deletion of the CR as before the database is dropped explicitly by the user. This could potentially solve all the permission assignments back and forth. What do you think?

**Comment by arnarg** [comment]
> One option would be to retain master role (non-login group role created by the operator) created by Postgres CR, as long as the database itself exists. This means that Postgres CR should have a finalizer that would prevent deletion of the CR as before the database is dropped explicitly by the user. This could potentially solve all the permission assignments back and forth.

So the finalizer does nothing unless the database has been dropped manually?

> I think this problem should be solved by more generic approach, or differnet aproach entirely. In this case it is tables, but the same thing applies for sequences, stored procedures, schemas, etc.

I was a aware that those things apply as well but I wanted to start somewhere.

Then there's the question of what do we want to happen when moving an already populated database into this operator? Do we expect users to manually fix the permissions?

I for one will be moving some applications into Kubernetes and would like the operator to handle this somehow.

**Comment by hitman99** [comment]
> So the finalizer does nothing unless the database has been dropped manually?

Well, operator could reject deletion operation with an error, if the database still exists, but this would just trigger a retry - I need to research on how to handle this properly.

> Then there's the question of what do we want to happen when moving an already populated database into this operator? Do we expect users to manually fix the permissions?
> 
> I for one will be moving some applications into Kubernetes and would like the operator to handle this somehow.

For existing databases to be used with operator I see two options:

- define a new property `masterRole` in `Postgres.spec` which would prevent auto-generated group role and just use that instead
- create a master group role in advance for the database (if it does not exist) before creating `Postgres` CR. This way it will try to create it and fail silently 

This new behaviour would also mean that the reassignment to the Postgres or AWS RDS root role on `Postgres` CR deletion would not be needed any more. After database is deleted, there would be nothing left to assign.

**Comment by hitman99** [comment]
As far as I can see there is no way to revert the deletion if it was initiated. So the solution might be to set a timeout in `reconcile.Result` for retry, so it would not spam operator's log with failed requeue attempts. It would be nice to indicate the user that deletion is failing somehow, but I don't see how would it be possible to communicate this message back to the action originator (`kubectl`)

**Comment by arnarg** [comment]
> Well, operator could reject deletion operation with an error, if the database still exists, but this would just trigger a retry - I need to research on how to handle this properly.

It can be useful in CI clusters to have a pre-populated database that doesn't need to be dropped on teardown of the cluster.

> define a new property masterRole in Postgres.spec which would prevent auto-generated group role and just use that instead

I like that option. `PostgresUser` can then just be granted that role without any code changes (to PostgresUser).

I vote for (at least the possibility of) that on CR deletion the operator just leaves the database and the group-role in place. Re-creating it will just be a no-op anyway as we're already ignoring `duplicate_database` and `duplicate_object` on database creation and group role creation respectively. This can be a default behavior or an option in spec.

What do you think?

**Comment by arnarg** [comment]
Something like this?
```yaml
apiVersion: db.movetokube.com/v1alpha1
kind: Postgres
metadata:
  name: my-db
  namespace: app
spec:
  database: test-db # Name of database created in PostgreSQL
  masterRole: existing-owner-role # An existing role that owns the database, optional
  finalizer: false # Omits even creating a finalizer, database and owner role will be left on deletion, optional
```

**Comment by arnarg** [comment]
Except a finalizer should probably always be there to make sure all `PostgresUser` CRs depending on it are deleted first, which isn't being enforced now either.

**Comment by hitman99** [comment]
Yes, exactly. This way the master role management will be out of scope.
Maybe instead of spec.finalizer, "keepResources" would be more user friendly

**Comment by hitman99** [comment]
That is fine as `PostgresUser` has it's own controller and reconciler loop. `keepResources` (or finalizer) would only be in spec of `Postgres` CR

**Comment by arnarg** [comment]
> Maybe instead of spec.finalizer, "keepResources" would be more user friendly

I like that.

> That is fine as PostgresUser has it's own controller and reconciler loop. keepResources (or finalizer) would only be in spec of Postgres CR. Instead of manual check for dependencies, we could add ownerReference to let Kubernetes do the cleaning

Yeah makes more sense :)

Then the question is would `keepResources` default to true or false? I'd argue true as that's less dangerous.

**Comment by hitman99** [comment]
I agree with you. Setting it to true is safer :)

Regards,
Tomas

**Comment by arnarg** [comment]
Nice, love it!

Should I split this into 2 issues and close this one?

Also when `keepResources` is false, should it drop the role and database or just refuse to delete the CR until the database is dropped?

**Comment by hitman99** [comment]
I think when the `keepResources` is false it should drop the database and role. This will happen if user specifically sets it to true, so it's assumed that he/she knows what this means. Yeah, you can close this issue and open an ew one. I could actually work on the `ownerReference` thing for `PostgresUser`, as I have some time to spare tomorrow.

**Comment by arnarg** [comment]
Closing this in favor of #10, #11 and #12

> I could actually work on the ownerReference thing for PostgresUser, as I have some time to spare tomorrow.

Sounds good!
