### ISSUE TITLE
Problem with Postgres URI Args

### ISSUE THREAD

**Issue by KarelNiine** [movetokube/postgres-operator#88]
line:
config.PostgresUriArgs = url.QueryEscape(utils.MustGetEnv("POSTGRES_URI_ARGS"))

url.QueryEscape Is replacing "sslmode=disable" with "sslmode%3Ddisable" and it wont work with postgresql.

operator gets error: "failed to connect to PostgreSQL server: pq: SSL is not enabled on the server"

**Comment by endersonmaia** [comment]
@KarelNiine you could use `v1.0.0`, since this `url.QueryEscape` was introduced just in `v1.1.0`, unless you have special characters for username, password or database name.

Just sent a PR (#89) to fix this, hope to get a `v1.1.1` version soon.

**Comment by rust84** [comment]
Seconded. I am using v1.0.0 for now.  Hopefully this will be merged soon 🙏
