### ISSUE TITLE
POSTGRES_URL should contain POSTGRES_URI_ARGS

### ISSUE THREAD

**Issue by reddec** [movetokube/postgres-operator#96]
I suppose that originally provided `POSTGRES_URI_ARGS` should also be included into the generated secrets

https://github.com/movetokube/postgres-operator/blob/e71c0d1c75a4888a8170d7859d07686c55663840/pkg/controller/postgresuser/postgresuser_controller.go#L266-L267

ex: `sslmod=disable`

I can make PR but it will not be very soon.

**Comment by gcaracuel** [comment]
I think it will be better to allow URI args, actually postgres connection params, per `PostgresUser` because there are some parameters that may change per client like `options`, `connect_timeout` and many others.

**Comment by reddec** [comment]
@gcaracuel I think it’s no more relevant - see https://github.com/movetokube/postgres-operator/pull/143
